# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            T.D.A
tagline:          'Projects Overview'
description:      'test description'
url:              http://thanujadax.github.io
baseurl:          /

author:
  name:           'Thanuja Ambegoda'
  url:            https://thanujadax.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/thanujadax

# Gems
gems: [jekyll-paginate,jekyll-gist]
